### ISSUE TITLE
parser.d references non-existant method `std.uni.unicode.parseSet`

### ISSUE THREAD

**Issue by RomanHargrave** [DmitryOlshansky/pry-parser#6]
At [line 35](https://github.com/DmitryOlshansky/pry/blob/master/src/pry/grammar/parser.d#L35) of `pry/grammar/parser.d`, `unicode.parseSet` is called.

This does not appear to exist in phobos, nor is it defined in Pry.

**Comment by DmitryOlshansky** [comment]
https://github.com/dlang/phobos/pull/5337

The pull that adds it to phobos. I thought it would take a week or two to merge it but it failed for months with some link-time error.

For now you could just merge it locally.

I'll do my best to get it merge now that it passes auto-tester.

**Comment by DmitryOlshansky** [comment]
Grammar mode is removed so can't be an issue anymore.
